# SPRING
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  application:
    name: ui-service

# SERVER
server:
  port: 8000
  context-path: /ui
  use-forward-headers: true

# EUREKA
eureka:
  instance:
      hostname: localhost
      port: 9050
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# SECURITY
auth-server: http://localhost:9999/uaa
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token

# LOGGING
logging:
  level:
    org.springframework.security: DEBUG

# ZUUL
zuul:
  routes:
    message:
      path: /api/messages/**
      url: http://localhost:7777/api/messages
