spring:
  application:
    name: discovery-service

# Define the port where the Service Registry server would be running
server:
  port: 9050

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry for server discovery
eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0


